export const PE_DATA = {
  JBH: {
    security: 'JBH',
    value: '0.55',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/JBH/valuation',
  },
  MLD: {
    security: 'MLD',
    value: '0.57',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/MLD/valuation',
  },
  AHY: {
    security: 'AHY',
    value: '1.34',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/AHY/valuation',
  },
  PGH: {
    security: 'PGH',
    value: '0.89',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/PGH/valuation',
  },
  NAB: {
    security: 'NAB',
    value: '4.09',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/NAB/valuation',
  },
  ADI: {
    security: 'ADI',
    value: '7.81',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/ADI/valuation',
  },
  TGR: {
    security: 'TGR',
    value: '1.49',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/TGR/valuation',
  },
  RFF: {
    security: 'RFF',
    value: '10.11',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/RFF/valuation',
  },
  RFG: {
    security: 'RFG',
    value: '1.29',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/RFG/valuation',
  },
  TLS: {
    security: 'TLS',
    value: '1.83',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/TLS/valuation',
  },
  SLK: {
    security: 'SLK',
    value: '2.08',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/SLK/valuation',
  },
  SHV: {
    security: 'SHV',
    value: '2.11',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/SHV/valuation',
  },
  ANZ: {
    security: 'ANZ',
    value: '4.10',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/ANZ/valuation',
  },
  CLH: {
    security: 'CLH',
    value: '1.47',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/CLH/valuation',
  },
  SOL: {
    security: 'SOL',
    value: '5.14',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/SOL/valuation',
  },
  IAG: {
    security: 'IAG',
    value: '1.77',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/IAG/valuation',
  },
  RIO: {
    security: 'RIO',
    value: '2.47',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/RIO/valuation',
  },
  CAR: {
    security: 'CAR',
    value: '8.67',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/CAR/valuation',
  },
  HPI: {
    security: 'HPI',
    value: '9.82',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/HPI/valuation',
  },
  ORI: {
    security: 'ORI',
    value: '1.27',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/ORI/valuation',
  },
  WPL: {
    security: 'WPL',
    value: '4.14',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/WPL/valuation',
  },
  QBE: {
    security: 'QBE',
    value: '0.89',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/QBE/valuation',
  },
  BWP: {
    security: 'BWP',
    value: '14.47',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/BWP/valuation',
  },
  CKF: {
    security: 'CKF',
    value: '0.94',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/CKF/valuation',
  },
  WOW: {
    security: 'WOW',
    value: '0.66',
    date: '20201122',
    source: 'https://www.morningstar.com/stocks/xasx/WOW/valuation',
  },
};

export const EPS_DATA = {
  JBH: {
    security: 'JBH',
    value: '2.61',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/JBH.ax?ltr=1',
  },
  MLD: {
    security: 'MLD',
    value: '-0.0660',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/MLD.ax?ltr=1',
  },
  AHY: {
    security: 'AHY',
    value: '0.0620',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/AHY.ax?ltr=1',
  },
  PGH: {
    security: 'PGH',
    value: '0.2570',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/PGH.ax?ltr=1',
  },
  NAB: {
    security: 'NAB',
    value: '0.81',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/NAB.ax?ltr=1',
  },
  ADI: {
    security: 'ADI',
    value: '0.2700',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/ADI.ax?ltr=1',
  },
  TGR: {
    security: 'TGR',
    value: '0.3390',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/TGR.ax?ltr=1',
  },
  RFF: {
    security: 'RFF',
    value: '0.1330',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/RFF.ax?ltr=1',
  },
  RFG: {
    security: 'RFG',
    value: '-0.0030',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/RFG.ax?ltr=1',
  },
  TLS: {
    security: 'TLS',
    value: '0.1530',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/TLS.ax?ltr=1',
  },
  SLK: {
    security: 'SLK',
    value: '-0.08',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/SLK.ax?ltr=1',
  },
  SHV: {
    security: 'SHV',
    value: '0.52',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/SHV.ax?ltr=1',
  },
  ANZ: {
    security: 'ANZ',
    value: '1.18',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/ANZ.ax?ltr=1',
  },
  CLH: {
    security: 'CLH',
    value: '-0.3120',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/CLH.ax?ltr=1',
  },
  SOL: {
    security: 'SOL',
    value: '3.98',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/SOL.ax?ltr=1',
  },
  IAG: {
    security: 'IAG',
    value: '0.19',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/IAG.ax?ltr=1',
  },
  RIO: {
    security: 'RIO',
    value: '4.41',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/RIO.ax?ltr=1',
  },
  CAR: {
    security: 'CAR',
    value: '0.47',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/CAR.ax?ltr=1',
  },
  HPI: {
    security: 'HPI',
    value: '0.2730',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/HPI.ax?ltr=1',
  },
  ORI: {
    security: 'ORI',
    value: '0.42',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/ORI.ax?ltr=1',
  },
  WPL: {
    security: 'WPL',
    value: '-4.40',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/WPL.ax?ltr=1',
  },
  QBE: {
    security: 'QBE',
    value: '-0.47',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/QBE.ax?ltr=1',
  },
  BWP: {
    security: 'BWP',
    value: '0.3280',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/BWP.ax?ltr=1',
  },
  CKF: {
    security: 'CKF',
    value: '0.27',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/CKF.ax?ltr=1',
  },
  WOW: {
    security: 'WOW',
    value: '0.92',
    date: '20201121',
    source: 'https://finance.yahoo.com/quote/WOW.ax?ltr=1',
  },
};
